-- table that will contain predefined companies
create table company
(
    id   bigint generated by default as identity,
    name varchar(200) not null,
    constraint pk_company primary key (id)
);

-- table that will contain predefined domains that cannot be used as part of e-mail addresses
create table blocklist
(
    id   bigint generated by default as identity,
    domain varchar(200) not null,
    constraint pk_blocklist primary key (id)
);

insert into company (name)
values ('Company #1'),
       ('Company #2'),
       ('Company #3');

insert into blocklist (domain)
values ('mailinator.com'),
       ('maildrop.cc'),
       ('trashmail.se');
